### ISSUE TITLE
Calculating across Sheets

### ISSUE THREAD

**Issue by bognarl** [fabiooshiro/xlsx-calc#1]
Hi @fabiooshiro,

I just came across this great lib, however I found out that this cannot handle calculations between Sheets. What do you think, could it be somehow possible? If so how?

Thanks in advance.

**Comment by fabiooshiro** [comment]
Yes its possible.
The point is here
https://github.com/fabiooshiro/xlsx-calc/blob/master/xlsx-calc.js#L529

Em 5 de dez de 2016 12:15 PM, "bognarl" <notifications@github.com> escreveu:

**Comment by fabiooshiro** [comment]
Hey @bognarl 
I made some changes, plz checkout the new version!
