### ISSUE TITLE
performance refinement

### ISSUE THREAD

**Issue by YJMLWZ** [fabiooshiro/xlsx-calc#119]
some formulars calculated twice, can be refined to improve performance.

e.g. formular[1] refer to formular[2], then in below loop we can skip re-calculate formular[2] 
https://github.com/fabiooshiro/xlsx-calc/blob/fb10a520cce5d7f2886e2eae3253b7650e55557b/src/index.js#L13

**Comment by fabiooshiro** [comment]
I think that we handle this situation. Take a look if there is some flag to tell that the cell is calculating, calculated, etc.

**Comment by fabiooshiro** [comment]
See the last commit please: https://github.com/fabiooshiro/xlsx-calc/commit/50a5c7975f3360337a2816abc657bf38ffbf1611

By the way, could you do some benchmark tests?
