### ISSUE TITLE
Incompatible implementations in formula.js

### ISSUE THREAD

**Issue by JeanAtAppsoluce** [fabiooshiro/xlsx-calc#13]
Hi everyone,

some functions from formula.js need an incompatible type to return the expected result, for example:

[MATCH impl](https://github.com/sutoiku/formula.js/blob/6e0845ee7c131c80eca7db5f87ef301b60bd6fae/test/lookup-reference.js#L9) expects an array of values, where xlsx will provide a Range (array of arrays), so MATCH will throw an error in our case.

I'm willing to make a PR fixing that issue, but i'm currently wondering which solution would be better.
If i modified XLSX_CALC.import_functions to not override formulas explicitely defined by XLSX_CALC, would that be an acceptable solution ? If not, how would you do ?

anyhow thanks for the cool lib !

**Comment by fabiooshiro** [comment]
Hi thx for your existence!

what about
`import_functions(fun, {override: false})`

the default is true cuz people should expect the last import 
or their function runs.

this is ok for you?

**Comment by fabiooshiro** [comment]
your solution already have an option.
I just change the name of option from "ignoreOverrides" to "override".
The default I agree to be false
default is immutability
