### ISSUE TITLE
"ref is an error with new formula" error thrown when executing a formula containing a number division by a blank cell

### ISSUE THREAD

**Issue by makdao** [fabiooshiro/xlsx-calc#16]
Hi,

When executing a formula containing a number division by a blank cell, it throws "ref is an error with new formula" error even though a checking on blank cell was done; however no similar error shown for a formula containing a number multiplication by blank cell. For example, where A1 is a blank cell and A2 is a formula,

1) =IF(AND(ISNUMBER(A1),A1<>0),**100/A1**,"Number cannot be divided by 0")
=> throw error "ref is an error with new formula A2" instead of showing "Number cannot be divided by 0"

2) =IF(AND(ISNUMBER(A1),A1<>0),**100*A1**,"Number cannot be 0")
=> cell A2 shows expected "Number cannot be 0"

Btw, thanks for writing this nice xlsx calculator for js :)

**Comment by fabiooshiro** [comment]
Hi makdao,

try the version xlsx-calc@0.5.6

> Btw, thanks for writing this nice xlsx calculator for js :)

magina!
