### ISSUE TITLE
Combining with formula.js?

### ISSUE THREAD

**Issue by callcthulhu** [fabiooshiro/xlsx-calc#2]
https://github.com/sutoiku/formula.js has other excel functions

**Comment by fabiooshiro** [comment]
seems perfect!

I will see with care later after carnival
thx a lot

Em 23 de fev de 2017 4:32 AM, "callcthulhu" <notifications@github.com>
escreveu:

**Comment by fabiooshiro** [comment]
its all over!
https://github.com/fabiooshiro/xlsx-calc#formulajs-integration
