### ISSUE TITLE
formula TEXT(DateCell;"ddd") should return day name as a text

### ISSUE THREAD

**Issue by JeanAtAppsoluce** [fabiooshiro/xlsx-calc#23]

**Comment by fabiooshiro** [comment]
maybe the formulajs has that implementation...

**Comment by JeanAtAppsoluce** [comment]
[they say their implementation is incomplete](https://github.com/sutoiku/formula.js/blob/d13ec90a250dc29d9c031f3a996a04f7fd66a58c/lib/text.js#L277) hopefully i'll get to work on this soon

**Comment by JeanAtAppsoluce** [comment]
i closed the issue by mistake !

**Comment by fabiooshiro** [comment]
I started a new repo for that function... take a look plz
https://github.com/fabiooshiro/text
