### ISSUE TITLE
Support for Sheet with spaces in name

### ISSUE THREAD

**Issue by olivierchatry** [fabiooshiro/xlsx-calc#24]
Hello !
First thanks a lot for doing this library.

I have a small issue with one of my files, some the sheets have names with spaces, that are put between `'`. For example : `='This is a sheet'!$F$4*L267*1.04` Will make the software crash.

I have try to fix it myself, by changing `exec_formula.js`, function build_expression like this :

```javascript
    formula.status = 'working';
    var root_exp;
    var str_formula = formula.cell.f;
    if (str_formula[0] == '=') {
        str_formula = str_formula.substr(1);
    }
    var exp_obj = root_exp = new Exp(formula);
    var buffer = '',
        is_string = false,
        was_string = false,
        is_string_spreadsheet = false
        ;

    var fn_stack = [{
        exp: exp_obj
    }];
    for (var i = 0; i < str_formula.length; i++) {
        if (str_formula[i] == '"' || str_formula[i] == "'") {
            is_string_spreadsheet = str_formula[i] == "'"
            if (is_string) {
                if (is_string_spreadsheet) {
                    exp_obj.push(buffer);
                } else {
                    exp_obj.push(new RawValue(buffer));
                }
```

It made the parsing go a bit further, but crash when evaluating some function :

In Exp.js :

```javascript
    function checkVariable(obj) {
        if (typeof obj.calc !== 'function') {
            throw new Error('Undefined ' + obj);
        }
    }
```

I guess somehow the lib does not recognize the call to the sheet. The formula that crash is this one: 

`='This is a sheet'!$F$4*L267*1.04`

I'm going to continue investigating that, but if  you have any pointers that might help, would be super cool.

Thanks again for this library !

**Comment by fabiooshiro** [comment]
Hi @olivierchatry 
Sorry for the delay
I did a commit with /test/tias.xlsx and /test/3-integrated-tests.js (see below)

```js
it('handles the sheet name', function() {
    var workbook = XLSX.readFile('test/tias.xlsx');
    erase_values_that_contains_formula(workbook.Sheets);
    var original_sheet = XLSX.readFile('test/tias.xlsx').Sheets.Sheet2;
    XLSX_CALC(workbook);
    assert_values(original_sheet, workbook.Sheets.Sheet2);
});
```

On my computer works :-D

**Comment by olivierchatry** [comment]
I will check, but the issue is with sheet with spaces in names.

**Comment by fabiooshiro** [comment]
I know, see the file ;-)

**Comment by olivierchatry** [comment]
Will do, thank you. I will try to see what is wrong with my Excel file and
come back.

**Comment by olivierchatry** [comment]
Yep, found the issue.

If you change the name to `Test - sheet` then it fails. I guess `-` might be the issue. ( I had to change the name if the sheet in my sample, should have checked with the new name, I'm sorry ).

**Comment by fabiooshiro** [comment]
could you try the last commit?

**Comment by olivierchatry** [comment]
It works ! But now I have a new issue, with IFs, using a reference to a cell that contains an equality test. Opening a new case and closing this one.

Thanks a lot again.
