### ISSUE TITLE
null is equal 0 in excel

### ISSUE THREAD

**Issue by olivierchatry** [fabiooshiro/xlsx-calc#27]
Seems like null value is equal to 0 in excel. I think there is a need for type checking / convertion, but I'm not sure if the cell type information is available.

**Comment by fabiooshiro** [comment]
take a look at integrated tests `test/3-integrated-test.js` write a test with some xlsx file plz
It would be nice!

**Comment by olivierchatry** [comment]
I will !

**Comment by fabiooshiro** [comment]
Hi @olivierchatry check the commit https://github.com/fabiooshiro/xlsx-calc/commit/119d690b6e8a02e4b4caf3a61b3dc983b6125742 plz
