### ISSUE TITLE
Excel string comparison is case insensitive

### ISSUE THREAD

**Issue by olivierchatry** [fabiooshiro/xlsx-calc#28]
From Excel documentation, it seems that string comparison are case insensitive. You have to use the EXACT macro to make it case sensitive.

( Going to write tests as soon as I have a bit of time, just filling up what I find )

https://exceljet.net/formula/compare-two-strings

**Comment by fabiooshiro** [comment]
@olivierchatry LibreOffice is case sensitive...
Google Sheets is case insensitive...
2 x 1
long live democracy!

**Comment by fabiooshiro** [comment]
@olivierchatry take a look at https://github.com/fabiooshiro/xlsx-calc/commit/d4250bbec1f0b22861d3e4d77e8c66826baa8003 
Feel free to reopen!
