### ISSUE TITLE
Function CONCAT not found

### ISSUE THREAD

**Issue by JeanPlouin** [fabiooshiro/xlsx-calc#29]
When CONCAT is used in excel instead of CONCATENATE (or any localized version, which works), xlsx-calc raises an error, where excel understands.

**Comment by fabiooshiro** [comment]
Man, I think that its a lot of work...
what about if I make only the structure like:
```js
XLSX_CALC.localizeFunctions({
  CONCAT: "CONCATENATE"
})
```

**Comment by fabiooshiro** [comment]
@JeanPlouin I made that https://github.com/fabiooshiro/xlsx-calc/commit/4531f79538f32187ac2cce19d642365a296ebb65

I need someone to help me to take care of this repo, would you like to be a colaborator?

**Comment by fabiooshiro** [comment]
Are you French?

**Comment by JeanPlouin** [comment]
the localizeFunctions solutions works perfect.
Yes i could help with the repo no problem
and Yes i'm french ^^!

**Comment by fabiooshiro** [comment]
I sent an invitation to you!

Bienvenue!!
