### ISSUE TITLE
function NBCAR not found

### ISSUE THREAD

**Issue by JeanPlouin** [fabiooshiro/xlsx-calc#32]
i'm on it

**Comment by fabiooshiro** [comment]
it's LEN("text")?

https://support.office.com/en-us/article/len-lenb-functions-29236f94-cedc-429d-affd-b5e33d2c67cb

**Comment by fabiooshiro** [comment]
@JeanPlouin what's up?
I hope you're doing ok.
I will close this for now, feel free to reopen it.
