### ISSUE TITLE
Function SH33TJSERRX not found

### ISSUE THREAD

**Issue by staperney** [fabiooshiro/xlsx-calc#42]
Hi,
I have  the following error:
`Error: "Summary"!P8: Function preview!SH33TJSERRX not found`

In the sheet Summary, I have the function EOMONTH in P8 which is indeed not defined in xlsx-calc, but the error is strange here. 
Have anyone encountered it?
[EDIT] After further investigation, it is indeed EOMONTH function. What I do not understand is why it is written like that. It might come from the package js-xlsx. I will check that.

Thanks for the help!

**Comment by fabiooshiro** [comment]
Check the js-xlsx and feel free to reopen this issue
