### ISSUE TITLE
function TRANSPOSE not found

### ISSUE THREAD

**Issue by staperney** [fabiooshiro/xlsx-calc#43]
Hi,

I have faced a new undefined function but I do not know how to compute this one unfortunately...
the function is TRANSPOSE.
You apply it to a range of cells and the results gives you a range of cells transposed.

If someone has an idea, that would be of great help!

**Comment by fabiooshiro** [comment]
it is extremely complicated...

**Comment by staperney** [comment]
Yes i know. I have no idea how to deal with it yet...
I will open another issue for sumif but I do not know how to deal with it yet. It shouldn’t be so hard though

**Comment by fabiooshiro** [comment]
@staperney take a look at the naive impl https://github.com/fabiooshiro/xlsx-calc/commit/09c69cb4806a2793d65f59b5be9b11f60af40287
It's missing circular reference check

**Comment by staperney** [comment]
@fabiooshiro I tried it on my code but the expressionWithRange does not looks like what you expect. Indeed here is what I have:
[ [ 0.054271928754395245,
    { t: 'e', v: 7, f: '(K111-L108/L107)/L114', w: '#DIV/0!' },
    { t: 'e', v: 7, f: '(L111-M108/M107)/M114', w: '#DIV/0!' },
    { t: 'e', v: 7, f: '(M111-N108/N107)/N114', w: '#DIV/0!' } ] ]

So I have no .args, .formula or such things. Would you know why?

**Comment by fabiooshiro** [comment]
I have no idea...
write your sample in transpose.xlsx and write a test plz

**Comment by fabiooshiro** [comment]
@staperney I will close this
feel free to reopen as necessary
