### ISSUE TITLE
issue with sumproduct

### ISSUE THREAD

**Issue by staperney** [fabiooshiro/xlsx-calc#45]
Hi,

The sumproduct can be written this way in Excel:
SUMPROD(A1:A4;D1:D4).
But it can also be written like that:
SUMPROD((A1:A4)*D1:D4).

The result is the same in excel but it returns an error with the library as the argument length is 1. 
Doing SUM simply on (A1:A4)*D1:D4 does not work unfortunately.
Would there be a way to create a special case if arguments.length===1 then it would be needed to parse the arguments and look for a * and then return sumproduct with the new arguments being the ranges but separated.

**Comment by fabiooshiro** [comment]
@staperney did you see this https://github.com/sutoiku/formula.js ?

**Comment by fabiooshiro** [comment]
closing, feel free to reopen.
