### ISSUE TITLE
function SUMIF not found

### ISSUE THREAD

**Issue by staperney** [fabiooshiro/xlsx-calc#46]
Hi @fabiooshiro ,

I tried the following for the sumif function but I must admit it is not very clean:
```
function sumif(){

    let elementToSum = arguments[1];
    let sumResult = 0;

    [].slice.call(arguments)[0][0].forEach((elt,key) =>{

        if (elt!==null){
            if( elt.replace(/\'/g, "") === elementToSum){
                if (!isNaN([].slice.call(arguments)[2][0][key])){
                    sumResult += [].slice.call(arguments)[2][0][key]
                } 
            }
        }
    });
    return sumResult
}
```

first arg is the range to be checked
second arg is the element to be checked
third arg is the range to be summed.

**Comment by fabiooshiro** [comment]
@staperney do you know TDD? Its awesome! The computer checks the results for you making you more confident to rewrite all system if you want

**Comment by fabiooshiro** [comment]
So thank you again!
