### ISSUE TITLE
NPM version is outdated

### ISSUE THREAD

**Issue by caiobozato** [fabiooshiro/xlsx-calc#49]
Hello, I was using the xlsx-calc from NPM and was having an error related to .calc() function.
Investigating the code with my leader, we noticed the NPM package is outdated because when I used the version from the Github, the code worked correctly.

Could you please update the package on NPM?

Thanks in advance.

**Comment by fabiooshiro** [comment]
sure!

**Comment by fabiooshiro** [comment]
try 0.6.4
