### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by raedwulf** [fabiooshiro/xlsx-calc#5]
Hi,

Great work here - but I noticed there's no license file currently in the repository.
Could you add one or indicate somewhere in the README?

Cheers,
Ralph

**Comment by fabiooshiro** [comment]
Give me a star and choose some license.

**Comment by raedwulf** [comment]
Haha, done! [MIT](https://opensource.org/licenses/MIT) would be perfect.  Thanks!

**Comment by fabiooshiro** [comment]
done
