### ISSUE TITLE
Multiple Sheets Calculation

### ISSUE THREAD

**Issue by sc-laurence** [fabiooshiro/xlsx-calc#53]
Love your work, but just encounter a weird issue.

My object is the following
`{
  "Sheet1": {
    "!ref": "B3:B5",
    "B3": {
      "t": "n",
      "v": 30,
      "z": "General",
      "w": "30"
    },
    "B4": {
      "t": "n",
      "v": 60,
      "f": "20+Sheet2!B3",
      "z": "General",
      "w": "60"
    },
    "B5": {
      "t": "n",
      "v": 90,
      "f": "SUM(B3:B4)",
      "z": "General",
      "w": "90"
    },
    "!margins": {
      "left": 0.7,
      "right": 0.7,
      "top": 0.75,
      "bottom": 0.75,
      "header": 0.3,
      "footer": 0.3
    }
  },
  "Sheet2": {
    "B3": {
      "t": "n",
      "v": 40,
      "f": "10+Sheet1!B3",
      "z": "General",
      "w": "40"
    },
    "!margins": {
      "left": 0.7,
      "right": 0.7,
      "top": 0.75,
      "bottom": 0.75,
      "header": 0.3,
      "footer": 0.3
    },
    "!ref": "B3"
  }
}`

Where (B4 of Sheet 1) is dependent on (B3 of Sheet 2).
(B3 of Sheet 2) is dependent on (B3 of Sheet 1)
and (B5 of Sheet1) is the sum of B3-B4 of Sheet 1.

So if I update (B3 of Sheet1) it should update all the cells in the object. But I notice (B5 of Sheet 1), which is the sum, does not update.
Not sure if I am doing anything wrong? let me know

Thanks.

**Comment by fabiooshiro** [comment]
Thank you!

It's working for me
```js
let workbook = {};
workbook.Sheets = {
    "Sheet1": { "!ref": "B3:B5", 
        "B3": { "t": "n", "v": 30, "z": "General", "w": "30" },
        "B4": { "t": "n", "v": 60, "f": "20+Sheet2!B3", "z": "General", "w": "60" },
        "B5": { "t": "n", "v": 90, "f": "SUM(B3:B4)", "z": "General", "w": "90" }, "!margins": { "left": 0.7, "right": 0.7, "top": 0.75, "bottom": 0.75, "header": 0.3, "footer": 0.3 } },
    "Sheet2": { 
        "B3": { "t": "n", "v": 40, "f": "10+Sheet1!B3", "z": "General", "w": "40" }, "!margins": { "left": 0.7, "right": 0.7, "top": 0.75, "bottom": 0.75, "header": 0.3, "footer": 0.3 }, "!ref": "B3" } };
// console.log(workbook.Sheets.Sheet1.B5.v);
let S1B3 = 11; // <<--- change your value
let S2B3 = 10 + S1B3;
let S1B4 = 20 + S2B3;
let S1B5 = S1B3 + S1B4;
// console.log("S1B5", S1B5);
workbook.Sheets.Sheet1.B3.v = S1B3;
XLSX_CALC(workbook);
console.log(workbook.Sheets.Sheet1.B5.v === S1B5); // aways true
```

**Comment by fabiooshiro** [comment]
There is no circular ref
https://csacademy.com/app/graph_editor/
![Graph Editor](https://user-images.githubusercontent.com/218768/73036996-1761f400-3e2c-11ea-91c7-0580ba5d2caa.png)

**Comment by fabiooshiro** [comment]
If you love the work...
 give it a star plz ;-)

**Comment by sc-laurence** [comment]
Definitely Starred.
Hmm might be something wrong with my build then. 

I am looking at the code and trying to determine how you find all the dependents and the precedents of the formula, would you share some liight in terms of the algorithm or the thinking?

Sorry to bother you, what I am trying to do is to improve the calculation speed by providing the function a new object that does not have the irrelevant cells to worry about, but I am failing to do so to be honest. So wondering if there is class or function that I can export from your package that would do that.

**Comment by fabiooshiro** [comment]
I will try, my english isnt that good...

```
step 1: get all cells with formulas
step 2: for each formula cell do:
          mark as computing...
step 3:   start the eval of the formula:
            the formula ref to another cell?
              yes: 
                is ref computing?
                  yes: throw circ exeption
                else
                  mark ref as computing... (go step 3)

```

**Comment by sc-laurence** [comment]
Awesome thanks so much. I might be just doing some of these wrong will redo my code. 

Thank man you are awsome 🥇

**Comment by fabiooshiro** [comment]
maybe that way is faster
https://github.com/fabiooshiro/xlsx-calc/blob/master/test/4-super-var.tests.js

**Comment by fabiooshiro** [comment]
I also check if the ref is already calculated, if so, I just get the value.
I don't calc 2x the same formula.

**Comment by sc-laurence** [comment]
Just wondering if you can set a variable, e.g. changed onto the worksheet obj where you can calculate only the cells that are changed and the related cells to it?

**Comment by sc-laurence** [comment]
Right now I am working recursively for that exact information, dependents and precendents cells of all the values that are changed, then create a new work sheet and pass through the XSLX_CALC function. But if that can be incooperated into the the XSLX_CALC which is doing the recursive call again, then I wont need to run the recursive twice.

**Comment by fabiooshiro** [comment]
> Just wondering if you can set a variable, e.g. changed onto the cell obj where you can calculate only the cells that are changed and the related cells to it?

reactive? that will be nice...
