### ISSUE TITLE
error while working with function contains curly braces {}

### ISSUE THREAD

**Issue by khalilcharfi** [fabiooshiro/xlsx-calc#56]
hi, I have a problem while having curly braces in the formula.
you can see below an example that produce  #N/A value (ref is an error after formula eval Page2!B31 #N/A).
https://drive.google.com/open?id=1mp10-YMg6yQYb_hhtct84cncB73zvsp3

**Comment by aymenbs2** [comment]
i have the same problem any solution please

**Comment by mejdi14** [comment]
did any one of you guys found solution for this because i have the same problem too

**Comment by khalilcharfi** [comment]
I use **SUMPRODUCT** as an alternative to the curly braces (it avoids the need of Ctrl-Shift-Enter)

**Comment by fabiooshiro** [comment]
Its a really complex problem

**Comment by khalilcharfi** [comment]
Hi, @fabiooshiro

I will send you tomorrow an example to explain all the attempts and the resulted outputs.

**Comment by fabiooshiro** [comment]
@khalilcharfi
