### ISSUE TITLE
Not working with named cell

### ISSUE THREAD

**Issue by jbouloux1** [fabiooshiro/xlsx-calc#61]
Hi,
If I use named cell in formula, XLSX_CALC(workbook) throws an error. No problem if I switch to real cells coordinates

**Comment by jbouloux1** [comment]
> Hi,
> If I use named cell in formula, XLSX_CALC(workbook) throws an error. No problem if I switch to real cells coordinates

Not sure if that's the best way to do it, but I managed to do what I wanted like this (for those who need the same behaviour)
`
var Calculator = require('./node_modules/xlsx-calc/src/Calculator');
var exec_formula = require('./node_modules/xlsx-calc/src/exec_formula');
        
let calc = new Calculator(wb, exec_formula);
calc.execute();`

**Comment by fabiooshiro** [comment]
Good!

**Comment by LOUKOUKOU** [comment]
I'm also getting a problem here, its not throwing an error, but my new value is NAN

**Comment by fabiooshiro** [comment]
try

```js
let calculator = XLSX_CALC.calculator(workbook);
calculator.setVar('first', 1);
calculator.execute();
```
