### ISSUE TITLE
OFFSET function cannot work with current parser

### ISSUE THREAD

**Issue by mcmar** [fabiooshiro/xlsx-calc#7]
I'm trying to use a spreadsheet that contains a formula like this: `=OFFSET(B15,1,0)`
I added a custom function called `OFFSET` that can take 3 variables and compute the new cell reference. But what I found was that `B15` was being computed and the result was passed to my offset function.

Here's the code that I wrote:
```
XlsxCalc.import_functions({
  OFFSET: function() {
    console.log('OFFSET', arguments);
    process.exit(1);
  },
});
XlsxCalc(workbook);
```

Here's what I expected:
```
$ node index.js financing.xlsx
OFFSET { '0': 'B15', '1': 1, '2': 0 }
```

Here's what I got:
```
$ node index.js financing.xlsx
OFFSET { '0': 'RATE', '1': 1, '2': 0 }
```

This is because `RATE` is the value of `B15`.

I think that `OFFSET` would require a special case to fix this. We would need to be able to allow functions to specify which of their params should be passed "raw" or "uncomputed".

**Comment by mcmar** [comment]
Update:
In addition to OFFSET, similar issues exist with functions like `VLOOKUP` and `HLOOKUP`

**Comment by fabiooshiro** [comment]
Hi @mcmar  

could be something like this?
```
    describe('raw function importer', function() {
        it('should sends the raw argument', function() {
            workbook.Sheets.Sheet1.A1 = { f: "OFFSET(A2,1,0)"};
            workbook.Sheets.Sheet1.A2 = { v: "RANGE"};
            XLSX_CALC.import_raw_functions({
                OFFSET: function(expr1, expr2, expr3) {
                    console.log(expr1.name); // Expression
                    console.log(expr1.args[0].name); // RefValue
                    console.log(expr1.args[0].str_expression); // A2
                    console.log(expr1.args[0].calc()); // RANGE
                    return [expr1.args[0].str_expression, expr2.calc(), expr3.calc()];
                },
            });
            XLSX_CALC(workbook);
            assert.deepEqual(workbook.Sheets.Sheet1.A1.v, ['A2',1,0]);
        });
    });
```

**Comment by fabiooshiro** [comment]
plz try the new version 0.3.5
