### ISSUE TITLE
Does this library do smart calculations of the formulas?

### ISSUE THREAD

**Issue by MartinDawson** [fabiooshiro/xlsx-calc#76]
So for example, if a user changes cell A1 and B1 depends on A1 does it automatically calculate A1 first and then B1?

Or is it just for parsing and executing the cell formula without any dependency tree calculation stuff?

I had a look at the source code of this library and can't find any dependency tree's being built but I just wanted to make sure.

Basically I'm using hyperformula right now to have quick calculations: https://handsontable.github.io/hyperformula/

And wondering if I can just use this library instead of it.

**Comment by fabiooshiro** [comment]
Yes sure

Em qua, 26 de mai de 2021 06:19, Martin Alex Philip Dawson <
***@***.***> escreveu:

**Comment by MartinDawson** [comment]
@fabiooshiro so what's the difference between this and hyperformula then? Do you have a demo/example of this package?

**Comment by fabiooshiro** [comment]
I dunno hyperformula :-(

Are you a programmer?

**Comment by MartinDawson** [comment]
Yes. I'm a programmer.

I see this file: https://github.com/fabiooshiro/xlsx-calc/blob/9b0d3198e1070d20275e0a340073760275fed74f/src/find_all_cells_with_formulas.js#L3

It's looping through all sheets and then all cells. So we can't use this library for dynamically updating individual cells on websites as it will be too slow.

This library is only for calculating the formulas when a user exports.

I.e this library is not building any tree's for efficient algorithm calculations like hyperformula does: https://handsontable.github.io/hyperformula/guide/key-concepts.html#phase-1-parsing-and-construction-of-asts

Which is fine I just wanted to clarify that, that's all.

**Comment by fabiooshiro** [comment]
Your file is huge?
A couple of years before I was doing risk calc with my lib and it was very
fast.
With excel it took 6hs to 8hs
With my lib less than 5min

Em qui, 27 de mai de 2021 07:39, Martin Alex Philip Dawson <
***@***.***> escreveu:

**Comment by fabiooshiro** [comment]
I know handsontable to draw an excel like table. It is really good!
Its nice that now they have a hyperformula.
For sure its better for you to get both lib working together than put hot with my lib

**Comment by MartinDawson** [comment]
Got it, I'll stick with hyperformula then.

Thanks for this library though, it's very useful to have an MIT/open source version for this calculation as its complicated.
