### ISSUE TITLE
Spaces after parentheses don't work

### ISSUE THREAD

**Issue by thetrevdev** [fabiooshiro/xlsx-calc#77]
```
    it('calcs form with space after parentheses', function() {
        workbook.Sheets.Sheet1.A1.f = '(1) *2';
        XLSX_CALC(workbook);
        assert.equal(workbook.Sheets.Sheet1.A1.v, 2);
    });
```
This fails with undefined.

| Formula  | Value |
| ------------- | ------------- |
| 1 * 2 | 2 |
| 1 * (2)  | 2  |
| (1)* 2  | 2  |
| (1)*2  | 2  |
| (1) *2  | undefined  |
| (1) * 2  | undefined  |

**Comment by thetrevdev** [comment]
This library is impressive with how far it has gotten me.  I tried to take a look at the code that might cause this issue but didn't make any progress.

**Comment by thetrevdev** [comment]
Actually I found a fix that passes all the tests I will put up a PR to review.  The expression builder default is to add the character to the buffer.  Skipping this in the case of a space works.  This default isn't hit when working directly with single or double quoted strings so references that include spaces still work.

**Comment by fabiooshiro** [comment]
Thx @thetrevdev 
Have a nice weekend
