### ISSUE TITLE
Cell with no value but used in a formula throws "Cell '[full-name-ref]' not found"

### ISSUE THREAD

**Issue by BaaptM** [fabiooshiro/xlsx-calc#8]
Hi @fabiooshiro !
I'm using xlsx-js to parse and write some values in a multiple sheets workbook which contains formulas that I need to recompute right after the value of a cell has been modified, then parse the new value and inject it somewhere else. 

Sometimes, formulas use cells with no values, checked with "IF(ISBLANK())".
In that case, I get the Error : Cell '[full-name-ref]' not found.

Do you have any idea how to fix that ?

Thanks !

**Comment by fabiooshiro** [comment]
send me your file plz

**Comment by BaaptM** [comment]
In this example attached, I need, for instance, to parse the workbook then update some cell, then recompute the first column. As you can see in the last column, some cells need to be empty.

[example.xlsx](https://github.com/fabiooshiro/xlsx-calc/files/1453178/example.xlsx)

**Comment by fabiooshiro** [comment]
try the new version 0.3.5

thx

**Comment by BaaptM** [comment]
Thanks a lot !
