### ISSUE TITLE
Strict equality

### ISSUE THREAD

**Issue by laucheukhim** [fabiooshiro/xlsx-calc#87]
In Excel,

`=0=""` is FALSE
`=0<>""` is TRUE

In xlsx-calc,

`=0=""` is TRUE
`=0<>""` is FALSE

See:
https://github.com/fabiooshiro/xlsx-calc/blob/e303d2096d1a1ffb127e26a8212212d5d1ce3f2f/src/Exp.js#L164
https://github.com/fabiooshiro/xlsx-calc/blob/e303d2096d1a1ffb127e26a8212212d5d1ce3f2f/src/Exp.js#L179

**Comment by fabiooshiro** [comment]
try v0.7.6
